// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPPFvy6b-QZu7lyIHVjfo9se8y-adHlfA',
    appId: '1:139690495228:web:a00957e847329c31625b79',
    messagingSenderId: '139690495228',
    projectId: 'artacho-dev',
    authDomain: 'artacho-dev.firebaseapp.com',
    storageBucket: 'artacho-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSFM8KNLQLdZITxxjy-E-RN5JcIm27Bks',
    appId: '1:139690495228:android:3955c3699a84359c625b79',
    messagingSenderId: '139690495228',
    projectId: 'artacho-dev',
    storageBucket: 'artacho-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWNaScOWlxE2QGbatKrvFXbPJU7lrBx10',
    appId: '1:139690495228:ios:e4d7dbde872d16bc625b79',
    messagingSenderId: '139690495228',
    projectId: 'artacho-dev',
    storageBucket: 'artacho-dev.firebasestorage.app',
    iosBundleId: 'com.artacho.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWNaScOWlxE2QGbatKrvFXbPJU7lrBx10',
    appId: '1:139690495228:ios:2856adb94a76d4fd625b79',
    messagingSenderId: '139690495228',
    projectId: 'artacho-dev',
    storageBucket: 'artacho-dev.firebasestorage.app',
    iosBundleId: 'com.example.holaMundoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPPFvy6b-QZu7lyIHVjfo9se8y-adHlfA',
    appId: '1:139690495228:web:4ff35f6695620f9e625b79',
    messagingSenderId: '139690495228',
    projectId: 'artacho-dev',
    authDomain: 'artacho-dev.firebaseapp.com',
    storageBucket: 'artacho-dev.firebasestorage.app',
  );
}
